### PR TITLE
Adds fees estimation for podcast creation

### LINKED ISSUE #48: UX Enhancement
## About
Show an error when the uploader has no AR or a non-sufficient balance to create the storage transaction.

## Additional UX
When this error occurs, ask them (in the error pop-up) to join the Telegram group of Permacast to get them AR (non-automated & a permissioned faucet)

### PR DESCRIPTION
**Pull request by maxknivets**
Now, if you try to create a new podcast, you will get an error popup saying how much the transaction costs.
This PR should close #48

### CODE REVIEW

**Review by charmful0x — CHANGES_REQUESTED** [review]
Hello @maxknivets !
Thanks for the PR, LGTM so far :)

Can you please also add the fee estimation feature for episode creation too?

**Review by charmful0x — COMMENTED** [review]
Hello @maxknivets , seems like there are errors with the fee calculation function. E.g. I tried to upload a 30.8 MiB audio file and the popup said that I needed 6.6 AR.

So it requires either fixing it or using [`canUpload()`](https://github.com/Parallel-news/arweave-fees.js#3--checking-the-ability-to-post-a-transaction) method from `arweave-fees.js` library. This method auto-calculated the `fee_multiplier` used in the app and in Arconnect extension. You just need to pass the TX object before requesting the TX signing.

**Comment by maxknivets** [comment]
Thanks for the feedback! Will fix this soon.

**Review by charmful0x — APPROVED** [review]
LGTM!

**Pull request merged**
