### PR TITLE
New UI with TailwindCSS

### PR DESCRIPTION
**Pull request by daoleno**
New design with TailwindCSS. 
Mobile friendly

### CODE REVIEW

**Comment by daoleno** [comment]
https://permacast-ui.herokuapp.com/

**Comment by daoleno** [comment]
@xylophonez Fixed

**Comment by charmful0x** [comment]
Hello @daoleno , thank you for the fixes and this nice UI :)

However, I was testing an episode upload using your Heroku deployment. However, it was breaking:

image

Tested on: 
https://permacast-ui.herokuapp.com/#/podcasts/AyENHKvl57vNvoY0rXna4W9h01HirbljLD1mYnvGdEU

Then, successfully uploaded from:
https://permacast.net/#/podcasts/AyENHKvl57vNvoY0rXna4W9h01HirbljLD1mYnvGdEU

Can you please test creating a podcast and then, upload an episode from the UI/branch you're working on? Feel free to drop your AR wallet address (here or via Telegram) so we cover the testing cost too :)

**Comment by daoleno** [comment]
@charmful0x I think the episode uploads have been fixed. Try it again.

**Review by charmful0x — COMMENTED** [review]
LGTM! @xylophonez do you still have any comments?

**Pull request merged**
